# Site settings
title: yg
header-img: img/home-bg.jpg
email: guya00@gmail.com
description: "Done is better than perfect."
baseurl: ""
url: "http://yg-park.github.io"
twitter_username: p_yg7
github_username:  yg-park
facebook_username:  guya00

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

kramdown:
    input: GFM
